### ISSUE TITLE
php7 - variable handling issue on import

### ISSUE THREAD

**Issue by gingebaker** [adrianbj/TableCsvImportExport#1]
Hi

I stumbled across a problem while testing the new ProFieldsTable v14 with this Import Module.
On CSV Import it adds the correct amount of rows but all of them have empty values.

This issue only occurs with PHP7.

After enabling debug it gave me following PHP Notice...
Notice: Indirect modification of overloaded property TableRow::$Array has no effect in 
( https://github.com/adrianbj/TableCsvImportExport/blob/master/TableCsvImportExport.module#L339 )

I nailed it down to the new variable handling of PHP7:
http://php.net/manual/de/migration70.incompatible.php#migration70.incompatible.variable-handling

The curly braces are needed. for example:
 $tableEntry->$subfieldNames[$subfieldKey] =
to:
 $tableEntry->{$subfieldNames[$subfieldKey]} =

I added curly braces in the if/else section from Line 327 to 339:

``` php
if($fieldType == 'pageSelect' || $fieldType == 'pageRadios') {
                        $tableEntry->{$subfieldNames[$subfieldKey]} = wire('pages')->get("{$fieldSelector}, title={$fieldValue}")->id;
                    }
                    elseif($fieldType == 'pageSelectMultiple' || $fieldType == 'pageAsmSelect' || $fieldType == 'pageCheckboxes') {
                        foreach(explode($importMultipleValuesSeparator, $fieldValue) as $title) {
                            $tableEntry->{$subfieldNames[$subfieldKey]}->add(wire('pages')->get("{$fieldSelector}, title={$title}")->id);
                        }
                    }
                    elseif($fieldType == 'selectMultiple') {
                        $tableEntry->{$subfieldNames[$subfieldKey]} = explode($importMultipleValuesSeparator, $fieldValue);
                    }
                    else {
                        //$tableEntry->$subfieldNames[$subfieldKey] = $convertDecimals == true ? $this->convertDecimals($fieldValue) : $fieldValue; // old, does not work in php7
                        $tableEntry->{$subfieldNames[$subfieldKey]} = $convertDecimals == true ? $this->convertDecimals($fieldValue) : $fieldValue; // new with curly braces
                        //$tableEntry->set($subfieldNames[$subfieldKey],$convertDecimals == true ? $this->convertDecimals($fieldValue) : $fieldValue); // would work also
                    }
```

after that the column values are imported correctly. At least for last "else". I didn´t test all of the other "elseif" statements, but it should be good to go...

can you confirm this issue?
regards, tom

**Comment by adrianbj** [comment]
Thanks @gingebaker - I have applied your curly brace fixes. Please let me know if you have any further  troubles.
