### ISSUE TITLE
Call to a member function add() on null

### ISSUE THREAD

**Issue by tbba** [adrianbj/TableCsvImportExport#3]
I exported a CSV and re-imported it and got an  error (also with fresh data):
File: .../TableCsvImportExport.module.php:463
Call to a member function add() on null

The PageTable Field has the following columns:
-Text
-Tiny Integer Unsigned
-Textarea
-Page (Select Multiple/Sortable ASM)
-Page (Select Multiple/Sortable ASM)

--
PW 3.0.126
TableCsvImportExport 2.0.8
PHP 7.2

**Comment by adrianbj** [comment]
Hi @tbba - sorry about that - looks like I broke that when I introduced support for pagination in the table field. Should be all fixed now. Please let me know if you still have any problems with it.

**Comment by tbba** [comment]
Yes - works again! - Thank you!!!!!
